spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/em
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 1000
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000
        # show_sql: true
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
file:
  root-path: C:/file-test
logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace
